config/routes.rb
# require 'sidekiq/web'

Yonodesperdicio::Application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # authenticated :admin_user do
  #   mount Sidekiq::Web, at: "/sidekiq"
  # end

  root 'home#index'

  get '/noticias/(:tag)', to: 'home#noticias', as: 'noticias'
  get '/noticia/:id', to: 'home#noticia', as: 'noticia'
  post '/noticia/:id/comments', to: 'comments#create', as: 'noticia_comments', commentable_type: 'Article', article_category: 'noticia'

  get '/iniciativas_sociales/(:tag)', to: 'home#iniciativas_sociales', as: 'iniciativas_sociales'
  get '/iniciativa_social/:id', to: 'home#iniciativa', as: 'iniciativa'
  post '/iniciativa_social/:id/comments', to: 'comments#create', as: 'iniciativa_comments', commentable_type: 'Article', article_category: 'iniciativa'

  get '/ideas/(:category)', to: 'home#ideas', as: 'ideas'
  get '/ideas/de/:tag', to: 'home#ideas_tag', as: 'ideas_tag'
  get '/idea/:id', to: 'home#idea', as: 'idea'
  post '/idea/:id/comments', to: 'comments#create', as: 'idea_comments', commentable_type: 'Idea'

  get '/organizaciones', to: 'home#organizations', as: 'organizations'
  get '/organizacion/:id', to: 'home#organization', as: 'organization'

  get '/particulares', to: 'home#particulares', as: 'particulares'

  scope '/page' do
    get '/funciona', to: 'page#funciona', as: 'funciona'
    get '/faqs', to: 'page#faqs', as: 'faqs'
    get '/legal', to: 'page#legal', as: 'legal'
    get '/tos', to: 'page#tos', as: 'tos'
    get '/about', to: 'page#about', as: 'about'
    get '/privacy', to: 'page#privacy', as: 'privacy'
    get '/translate', to: 'page#translate', as: 'translate'
    get '/sitemap', to: 'page#sitemap', as: 'sitemap'
  end

  namespace :api, defaults: { format: :json } do
    get 'total_kg', to: 'base#total_kg'
    get 'categories', to: 'base#categories'
    get '', to: 'base#index'
    resources :users, :only => [:show, :create, :update, :destroy] do
      post 'rate', on: :member
    end
    resources :sessions, :only => [:create, :destroy]
    resources :ideas do
      resources :comments, :only => [:create]
    end
    resources :ads do
      resources :comments, :only => [:create]
    end
    resources :offers
    resources :mailboxes, :only => [:show] do
      resources :conversations, :only => [:index, :show] do
        resources :messages, :only => [:index, :create]
      end
    end
    get '/conversations', to: 'conversations#conversations'
    post '/new_message/(:recipient_id)', to: 'messages#new_message'
  end

  resources :ideas, path: 'mis_ideas', as: 'my_ideas'

  # FIXME: type on ads#create instead of params
  # FIXME: nolotirov2 legacy - redirect from /es/ad/create
  resources :ads, path: 'ad', path_names: { new: 'create' }

  scope '/ad' do
    #get '/create', to: redirect('/ad/create/type/1')
    get '/:id/:slug', to: 'ads#show', :as => 'adslug'
    get '/edit/id/:id', to: 'ads#edit', :as => 'ads_edit'
    get '/listall/ad_type/:type', to: 'woeid#show', as: "ads_listall"
    get '/listall/ad_type/:type/status/:status', to: 'woeid#show', as: 'ads_listall_status'
    get '/listall/page/:page/ad_type/:type', to: redirect('/ad/listall/ad_type/%{type}?page=%{page}')
    get '/listuser/id/:id', to: 'users#listads', as: 'listads_user'
  end

  resources :offers

  # locations lists
  get '/woeid/:id/:type', to: 'woeid#show', as: 'ads_woeid'
  get '/woeid/:id/:type/page/:page', to: redirect('/woeid/%{id}/%{type}?page=%{page}')
  get '/woeid/:id/:type/status/:status', to: 'woeid#show', as: 'ads_woeid_status'
  get '/woeid/:id/:type/page/:page/status/:status', to: redirect('/woeid/%{id}/%{type}/status/%{status}?page=%{page}')

  # location change
  scope '/location' do
    get  '/change', to: 'location#ask', as: 'location_ask'
    get  '/change2', to: 'location#change', as: 'location_change'
    post '/change', to: 'location#list'
    post '/change2', to: 'location#change'
  end

  # auth
  get '/auth/login', to: redirect('/es/user/login')
  get '/user/forgot', to: redirect('/es/user/reset/new')

  devise_for :users,
    :controllers => { :registrations => 'registrations' },
    path: 'user',
    path_names: {
      sign_up: 'register',
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset'
  }

  post '/addfriend/id/:id', to: 'friendships#create', as: 'add_friend'
  post '/deletefriend/:id', to: 'friendships#destroy', as: 'destroy_friend'

  scope '/admin' do
    get '/become/:id', to: 'admin#become', as: 'become_user'
    get '/lock/:id', to: 'admin#lock', as: 'lock_user'
    get '/unlock/:id', to: 'admin#unlock', as: 'unlock_user'
  end

  get '/user/edit/id/:id', to: redirect('/user/edit'), as: 'user_edit'
  get '/profile/:username', to: 'users#profile', as: 'profile'

  # comments
  post '/ad/:id/comments', to: 'comments#create', as: 'create_comment', commentable_type: 'Ad'

  # search
  get '/search', to: 'search#search', as: 'search'

  # messaging
  resources :mailboxer_messages, controller: :messages, path: "/messages/" do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end

  post 'messages/search', to: 'messages#search', as: "search_mailboxer_messages"

  # messaging legacy
  scope '/message' do
    get  '/received', to: redirect('/es/message/list'), as: 'messages_received'
    get  '/list', to: 'messages#index', as: 'messages_list'
    get  '/show/:id/subject/:subject', to: 'messages#show', as: 'message_show'
    get  '/create/id_user_to/:user_id', to: 'messages#new', as: 'message_new'
    get  '/create/id_user_to/:user_id/subject/:subject', to: "messages#new", as: 'message_new_with_subject'
    post '/create/id_user_to/:user_id', to: 'messages#create', as: 'message_create'
    post '/create/id_user_to/:user_id/subject/:subject', to: "messages#create", as: 'message_create_with_subject'
    post '/reply/:id/to/:user_id', to: 'messages#reply', as: 'message_reply'
  end

  # rss
  # nolotirov2 - legacy
  # FIX: las URLs legacy vienen asi
  # /en                     /rss/feed/woeid/766273                     /ad_type/give
  # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
  # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
  scope '/rss' do
    get '/feed/woeid/:woeid/ad_type/:type', format: 'rss', to: 'rss#feed', as: 'rss_type'
    get '/feed/woeid/:woeid/ad_type/give/status/:status', format: 'rss', to: 'rss#feed', as: 'rss_status'
  end

  # contact
  get '/contact', to: 'contact#new', as: 'contacts'
  post '/contact', to: 'contact#create'

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < Api::BaseController
  include FCMPushNotifications

  before_action :authenticate_with_token!
  respond_to :json

  def index
    mailbox = set_mailbox
    messages = mailbox.find(params[:conversation_id]).messages.page(params[:page]).per(params[:per_page])
    render json: messages, meta: pagination(messages, params[:per_page])
  end

  def show
    mailbox = set_mailbox
    respond_with current_user.mailbox.conversations.find(params[:conversation_id])
  end

  def create
    conversation = current_user.mailbox.conversations.find(params[:conversation_id])

    if receipt = current_user.reply_to_conversation(conversation, params[:message][:body])
      FCMPushNotifications.delay.message_sent(receipt)
      render json: receipt
    else
      render json: { errors: receipt.errors }, status: 422
    end
  end

  def new_message
    recipient = User.find(params[:recipient_id])
    if receipt = current_user.send_message(recipient, params[:message][:body], params[:message][:subject])
      render json: receipt.message
    else
      render json: { errors: receipt.errors }, status: 422
    end
  end

  private

  def message_params
    params.require(:message).
    permit(:subject, :body)
  end

  def set_mailbox
    if params[:mailbox_id] == 'sent'
      current_user.mailbox.sentbox
    elsif params[:mailbox_id] == 'trash'
      current_user.mailbox.trash
    elsif params[:mailbox_id] == 'inbox'
      current_user.mailbox.inbox
    else
      current_user.mailbox.conversations
    end
  end
end

app/controllers/legacy/messages_controller.rb
class Legacy::MessagesController < ApplicationController

  before_filter :authenticate_user!

  # GET '/message/show/:id/subject/:subject'
  def show 
    @thread = Legacy::MessageThread.find params[:id]
  end

  # GET '/message/create/id_user_to/:user_id'
  # GET '/message/create/id_user_to/:user_id/subject/:subject'
  def new
    @user = User.find params[:user_id]
    @subject = params[:subject]
  end

  # POST '/message/create/id_user_to/:user_id'
  # POST '/message/create/id_user_to/:user_id/subject/:subject'
  def create
    @message = Legacy::Message.create_thread(
      current_user.id,
      params[:user_id],
      params[:message][:subject],
      params[:message][:body],
      request.remote_ip
    )
    if @message.save
      @user = User.find params[:user_id]
      MessagesMailer.create(
        @user.email,
        current_user.username,
        params[:message][:subject],
        params[:message][:body]
      ).deliver
      redirect_to message_show_path(@thread.id, @thread.subject.parameterize)
      render action: 'new'
    end
  end
  # POST '/message/reply/:id/to/:user_id'
  def reply
    # WIP  TODO
    @thread = Legacy::MessageThread.find params[:id]
    @user = User.find params[:user_id]

    @message = Legacy::Message.new(
      thread_id: @thread.id,
      ip: request.remote_ip,
      subject: @thread.subject,
      body: params[:body],
      user_from: current_user.id,
      user_to: @user.id
    )
    if @message.save
      MessagesMailer.create(
        @user.email,
        current_user.username,
        @thread.subject,
        params[:body]
      ).deliver
      redirect_to message_show_path(@thread.id, @thread.subject), notice: 'Message was successfully replied.'
    else
      # there was an error saving
      render action: 'new'

    end
  end

  # GET '/message/list'
  def list 
    @last_threads = Legacy::Message.get_threads_from_user(current_user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:thread_id, :ip, :subject, :body, :readed, :user_from, :user_to)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include FCMPushNotifications
  
  before_filter :authenticate_user!

  def index
    @box = params[:box] || 'inbox'
    @messages = current_user.mailbox.inbox if @box == 'inbox'
    @messages = current_user.mailbox.sentbox if @box == 'sent'
    @messages = current_user.mailbox.trash if @box == 'trash'
    @messages = current_user.mailbox.archive if @box == 'archive'
    @messages = @messages.sort_by {|m| m.messages.last.created_at}.reverse
    @messages = Kaminari.paginate_array(@messages).page(params[:page])
    session[:last_mailbox] = @box
  end

  def new
    @message = Mailboxer::Message.new
    @recipient = User.find(params[:user_id])
    if params[:user_id]
      @message.recipients = @recipient.id
    end
  end

  def create
    @message = Mailboxer::Message.new message_params
    @message.sender = current_user
    # FIXME: this should be on model (validation)
    if @message.sender.id == params[:mailboxer_message][:recipients].to_i
      return redirect_to message_create_url(user_id: params[:mailboxer_message][:recipients].to_i), notice: I18n.t("mailboxer.notifications.error_same_user")
    end
    if @message.conversation_id
      @conversation = Mailboxer::Conversation.find(@message.conversation_id)
      #@conversation = current_user.mailbox.conversations.find(@message.conversation_id)
      # FIXME: ACL should be on app/models/ability.rb
      unless @conversation.is_participant?(current_user) or current_user.admin?
        flash.now[:alert] = I18n.t('nlt.permission_denied')
        return redirect_to root_path
      end
      receipt = current_user.reply_to_conversation(@conversation, @message.body, nil, true, true, @message.attachment)
      send_notification(receipt)
    else
      @message.recipients = User.find(params[:mailboxer_message][:recipients])
      unless @message.valid?
        return render :new
      end
      receipt = current_user.send_message(@message.recipients, @message.body, @message.subject, true, @message.attachment)
      send_notification(receipt)
    end
    flash.now[:notice] = I18n.t "mailboxer.notifications.sent"
    redirect_to mailboxer_message_path(receipt.conversation)
  end

  # GET /messages/:ID
  # GET /message/show/:ID/subject/SUBJECT
  def show
    # TODO: refactor this
    @conversation = Mailboxer::Conversation.find_by_id(params[:id])
    #@conversation = current_user.mailbox.conversations.find(params[:id])
    # if not found, it could be a legacy URL with a ID for a legacy thread
    if @conversation.nil?
      @conversation = Legacy::MessageThread.find(params[:id]).conversation
    end
    raise ActiveRecord::RecordNotFound if @conversation.nil?
    # FIXME: ACL should be on app/models/ability.rb
    unless @conversation.is_participant?(current_user) or current_user.admin?
      flash[:alert] = I18n.t('nlt.permission_denied')
      return redirect_to root_path
    end
    @message = Mailboxer::Message.new conversation_id: @conversation.id
    current_user.mark_as_read(@conversation)
  end

  def move
    mailbox = params[:mailbox]
    conversation = current_user.mailbox.conversations.find(params[:id])
    if conversation
      current_user.send(mailbox, conversation)
      flash[:notice] = I18n.t "mailboxer.notifications.sent", mailbox: mailbox
    else
      conversation = current_user.mailbox.conversations.find(params[:conversations])
      conversations.each { |c| current_user.send(mailbox, c) }
      flash[:notice] = I18n.t "mailboxer.notifications.sent", mailbox: mailbox
    end
    redirect_to mailboxer_messages_path(box: params[:current_box])
  end

  def trash
    conversation = current_user.mailbox.conversations.find(params[:id] || params[:conversations])
    current_user.trash(conversation)
    flash[:notice] = I18n.t "mailboxer.notifications.trash"
    redirect_to mailboxer_messages_path(:box => 'inbox')
  end

  def untrash
    conversation = current_user.mailbox.conversations.find(params[:id])
    current_user.untrash(conversation)
    flash[:notice] = I18n.t "mailboxer.notifications.untrash"
    redirect_to mailboxer_messages_path(:box => 'inbox')
  end

  def search
    @search = params[:search]
    @messages = current_user.search_messages(@search)
    render :index
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:mailboxer_message).permit(:conversation_id, :body, :subject, :recipients, :sender_id)
  end

  def send_notification(receipt)
    FCMPushNotifications.delay(queue: "notifications").message_sent(receipt)
  end

end

app/helpers/message_helper.rb
module MessageHelper

  def other_username( current_user, m )
    sender = m.messages.first.recipients.first.username
    reciever = m.messages.first.recipients.second.username
    if current_user == sender
      reciever
    else
      sender
    end
  end

end

app/views/messages/_form.html.erb
<%= form_tag mailboxer_message_reply_path(thread, thread.other_user(user)) do  %>
  <dl class="zend_form">
    <dd id="body-element">
    <%= text_area_tag :body, '', :size => "80x3", maxlength: 2500 %>
    </dd>
    <div class="actions"><%= submit_tag t('mailboxer.new.button') %></div>
  </dl>
<% end %>

app/views/messages/_message.html.erb
<% if message.sender == message.conversation.messages.first.sender %>
  <div class="message-excerpt">
    <div class="message-from-left">
      <%= link_to profile_path message.sender do %>
        <%= image_tag message.sender.image.url(:thumb), :alt => "", :class => "img-responsive, avatar" %>
        <%= message.sender.username %>
      <% end %>
    </div>
    <div class="message-container-right">
      <div class="triangle-me">
      </div>
      <div class="bubble bg-bubble-me">
        <%= message.body %>
        <div class="message-date"> 
          <%= message.created_at.strftime("%d-%b-%Y  %T") %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="message-excerpt">
    <div class="message-from-right">
      <%= link_to profile_path message.sender do %>
        <%= image_tag message.sender.image.url(:thumb), :alt => "", :class => "img-responsive, avatar" %>
        <%= message.sender.username %>
      <% end %>
    </div>
    <div class="message-container-left">
      <div class="triangle-other">
      </div>
      <div class="bubble bg-bubble-other">
        <%= message.body %>
        <div class="message-date">
          <%= message.created_at.strftime("%d-%b-%Y  %T") %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/_reply.html.erb
<div class="message-excerpt">
  <div class="message-from-left">
    <%= link_to profile_path(current_user) do  %>
      <%= image_tag current_user.image.url(:thumb), :alt => "", :class => "img-responsive, avatar" %>
      <%= current_user.username  %>
    <% end %>
  </div>
  <div class="message-container-right">
    <div class="triangle-me"></div>
    <div class="bubble-reply bg-bubble-me">
      <div id="reply">
        <%= form_for message do |f| %>
          <%= f.hidden_field :conversation_id %>
          <%= f.text_area :body, size: '80x3', maxlength: 1500 %>
          <p class="description">
            <%= t 'mailboxer.new.body_max' %>
          </p>
          <div class="actions"><%= f.submit t('mailboxer.new.button') %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/_tabmessages.html.erb
<!-- TODO: can an user edit or view messages from another user? -->
<ul id="tabnav">
  <li><%= link_to_unless_current t('nlt.messages_tabs.inbox'), ( mailboxer_messages_path(box: 'inbox') || mailboxer_messages_path )  %></li>
  <li><%= link_to_unless_current t('nlt.messages_tabs.sent'), mailboxer_messages_path(box: 'sent') %></li>
  <li><%= link_to_unless_current t('nlt.messages_tabs.trash'), mailboxer_messages_path(box: 'trash')  %></li>
</ul>

app/views/messages/_thread.html.erb
<div class="thread_excerpt">
  <div class="thread-from">
    <h4>
      <% if defined? thread[1].username %>
        <%= link_to thread[1].username, profile_path(thread[1]) %>
      <% end %>
    </h4>
  </div>
  <div class="thread-messages">
    <%= thread[0].messages.count %>
    [<%= thread[0].unreaded_messages_count %>]
  </div>
  <div class="thread-subject">
    <%= link_to thread[0].subject, mailboxer_message_show_path(id: thread[0].id, subject: thread[0].subject) %>
  </div>
  <div class="thread-date">
    <%= distance_of_time_in_words_to_now thread[0].messages.last.created_at %>
  </div>
</div>

app/views/messages/index.html.erb
<% title = t('mailboxer.titles.index', username: current_user.username) %>
<%= content_for :meta_title, title %>

<%= render partial: "users/tabnav", locals: {user: current_user} %>

<div id="inside" class="col-md-12 col-sm-12 col-xs-12">
  <h1 class="title-listados"><%= title %></h1>

<div id="main">
  <div class="span-19" id="list-messages-profile">
    <%= render partial: "messages/tabmessages", locals: {box: @box} %>
    <% if @search %>
      <h2>
        <%= t('mailboxer.search', search: @search) %>
      </h2>
    <% end %>
    <% if @messages.count > 0 %>
      <%= form_tag trash_mailboxer_messages_path, method: :delete do %>
        <%= hidden_field_tag 'current_box', @box %>
        <div class="table-responsive">
          <table class="table table-condensed" id="mail-list">
            <tbody>
              <% @messages.each do |m| %>
                <tr class="mail <%=  'unread' if m.is_unread?(current_user)  %>">
                  <% unless @box == 'trash' %>
                    <td style="float:left;width:20px;">
                      <%= check_box_tag '', m.id, false, class: 'delete_multiple_checkbox', name: "conversations[]" %>
                    </td>
                  <% else %>
                    <td></td>
                  <% end %>
                  <td class="sender">
                    <%= cache "other_username-#{current_user.id}_#{m.id}" do %>
                      <%= other_username( current_user.username, m ) %>
                    <% end %>
                  </td>
                  <td class="mail-subject">
                    <%= link_to m.subject, mailboxer_message_path(m) %>
                  </td>
                  <td class="timestamp">
                    <%= cache "moment-#{m.messages}" do %>
                      <%= m.messages.last.created_at.strftime("%d-%b-%Y  %T") %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% unless @box == 'trash' %>
          <%= submit_tag t('mailboxer.buttons.trash_selected'), id: 'delete_multiple_button' %>
        <% end %>
      <% end %>
    <% else %>
      <p>
        <div class="info">
          <%= t("mailboxer.table.none") %>
        </div>
      </p>
    <% end %>
  </div>
</div>

</div><!--/newinside-->

app/views/messages/new.html.erb
<% title = t('mailboxer.new.title', user: @recipient.username) %>
<% content_for :meta_title, title %>

<div id="newinside" class="col-md-8 col-md-offset-2">
  <h1 class="title-listados"><%= title %></h1>

<div id="main">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <%= form_for @message do |f| %>
      <fieldset>
        <legend>
          <%= t('mailboxer.new.legend') %>
        </legend>
        <% if @message.errors.any? %>
          <div class="error">
            <h2>
              <%= t('mailboxer.new.errors', errors: pluralize(@message.errors.count, "error")) %>
            </h2>
            <ul>
              <% @message.errors.full_messages.each do |msg| %>
                <li>'#{ msg }'</li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <dl>
          <dt id="subject-label">
            <%= f.label :subject, t('mailboxer.new.subject') %>
          </dt>
          <dd id="subject-element">
            <% if params['subject'] %>
              <%= f.text_field :subject, value: params['subject'] %>
            <% else %>
              <%= f.text_field :subject %>
            <% end %>
          </dd><br/>
          <dd id="body-element">
            <%= f.text_area :body, size: '80x3', maxlength: 1500, required: true %>
            <p class="description">
              <%= t 'mailboxer.new.body_max' %>
            </p>
          </dd>
        </dl>
        <%= f.hidden_field :recipients %>
        <div class="actions"><%= f.submit t('mailboxer.new.submit') %></div>
      </fieldset>
    <% end %>
  </div>
</div>
</div><!--/newinside-->

app/views/messages/show.html.erb
<% title = t("mailboxer.titles.conversation", recipient: @conversation.recipients.first.username, subject: @conversation.subject) %>
<% content_for :meta_title, title %>

<div id="mensajescabecera" class="col-md-12 col.sm-12 col-xs-12">
  <h5><%= link_to t("mailboxer.buttons.back"), mailboxer_messages_path %></h5>
  <h1 class="enrojo"><%= title %></h1>
  <% if @conversation.is_trashed?(current_user) %>
    <%= link_to t("mailboxer.buttons.untrash"), untrash_mailboxer_message_path(@conversation), class: :button, method: :post %>
  <% else %>
    <%= link_to t("mailboxer.buttons.trash"), trash_mailboxer_message_path(@conversation), class: :button, method: :delete %>
  <% end %>
</div>

<div id="listamensajes">
  <div class="span-15" id="messages-thread">
    <% @conversation.messages.each do |mes| %>
      <%= render :partial => "message", :locals => {:message => mes} %>
    <% end %>
    <%= render :partial => "reply", :locals => {:message => @message} %>
    <br/>
  </div>
</div>

app/views/messages/show_old.html.erb
<div id="default_header_section">
  <h5><%= link_to "&lt; volver a mensajes", messages_list_path %></h5>
  <h1><%= @thread.subject %></h1>
</div>

<div id="main">
  <div class="span-15">
    <% @thread.messages.each do |message| %>
      <%= render :partial => "message", :locals => {:message => message} %>
    <% end %>
    <div class="message-excerpt">
      <div class="message-from-left">
        <%= link_to profile_path(current_user) do %>
          <%= image_tag "contact.png" %>
          <%= current_user.username %>
        <% end %>
      </div>
      <div class="message-container-right">
        <div class="triangle-me">
        </div>
        <div class="bubble-reply bg-bubble-me">
          <%= render :partial => "form", :locals => {:thread => @thread, :user => current_user} %>
          </div>
      </div>
    </div>
  </div>
</div>