config/routes.rb
# require 'sidekiq/web'

Yonodesperdicio::Application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # authenticated :admin_user do
  #   mount Sidekiq::Web, at: "/sidekiq"
  # end

  root 'home#index'

  get '/noticias/(:tag)', to: 'home#noticias', as: 'noticias'
  get '/noticia/:id', to: 'home#noticia', as: 'noticia'
  post '/noticia/:id/comments', to: 'comments#create', as: 'noticia_comments', commentable_type: 'Article', article_category: 'noticia'

  get '/iniciativas_sociales/(:tag)', to: 'home#iniciativas_sociales', as: 'iniciativas_sociales'
  get '/iniciativa_social/:id', to: 'home#iniciativa', as: 'iniciativa'
  post '/iniciativa_social/:id/comments', to: 'comments#create', as: 'iniciativa_comments', commentable_type: 'Article', article_category: 'iniciativa'

  get '/ideas/(:category)', to: 'home#ideas', as: 'ideas'
  get '/ideas/de/:tag', to: 'home#ideas_tag', as: 'ideas_tag'
  get '/idea/:id', to: 'home#idea', as: 'idea'
  post '/idea/:id/comments', to: 'comments#create', as: 'idea_comments', commentable_type: 'Idea'

  get '/organizaciones', to: 'home#organizations', as: 'organizations'
  get '/organizacion/:id', to: 'home#organization', as: 'organization'

  get '/particulares', to: 'home#particulares', as: 'particulares'

  scope '/page' do
    get '/funciona', to: 'page#funciona', as: 'funciona'
    get '/faqs', to: 'page#faqs', as: 'faqs'
    get '/legal', to: 'page#legal', as: 'legal'
    get '/tos', to: 'page#tos', as: 'tos'
    get '/about', to: 'page#about', as: 'about'
    get '/privacy', to: 'page#privacy', as: 'privacy'
    get '/translate', to: 'page#translate', as: 'translate'
    get '/sitemap', to: 'page#sitemap', as: 'sitemap'
  end

  namespace :api, defaults: { format: :json } do
    get 'total_kg', to: 'base#total_kg'
    get 'categories', to: 'base#categories'
    get '', to: 'base#index'
    resources :users, :only => [:show, :create, :update, :destroy] do
      post 'rate', on: :member
    end
    resources :sessions, :only => [:create, :destroy]
    resources :ideas do
      resources :comments, :only => [:create]
    end
    resources :ads do
      resources :comments, :only => [:create]
    end
    resources :offers
    resources :mailboxes, :only => [:show] do
      resources :conversations, :only => [:index, :show] do
        resources :messages, :only => [:index, :create]
      end
    end
    get '/conversations', to: 'conversations#conversations'
    post '/new_message/(:recipient_id)', to: 'messages#new_message'
  end

  resources :ideas, path: 'mis_ideas', as: 'my_ideas'

  # FIXME: type on ads#create instead of params
  # FIXME: nolotirov2 legacy - redirect from /es/ad/create
  resources :ads, path: 'ad', path_names: { new: 'create' }

  scope '/ad' do
    #get '/create', to: redirect('/ad/create/type/1')
    get '/:id/:slug', to: 'ads#show', :as => 'adslug'
    get '/edit/id/:id', to: 'ads#edit', :as => 'ads_edit'
    get '/listall/ad_type/:type', to: 'woeid#show', as: "ads_listall"
    get '/listall/ad_type/:type/status/:status', to: 'woeid#show', as: 'ads_listall_status'
    get '/listall/page/:page/ad_type/:type', to: redirect('/ad/listall/ad_type/%{type}?page=%{page}')
    get '/listuser/id/:id', to: 'users#listads', as: 'listads_user'
  end

  resources :offers

  # locations lists
  get '/woeid/:id/:type', to: 'woeid#show', as: 'ads_woeid'
  get '/woeid/:id/:type/page/:page', to: redirect('/woeid/%{id}/%{type}?page=%{page}')
  get '/woeid/:id/:type/status/:status', to: 'woeid#show', as: 'ads_woeid_status'
  get '/woeid/:id/:type/page/:page/status/:status', to: redirect('/woeid/%{id}/%{type}/status/%{status}?page=%{page}')

  # location change
  scope '/location' do
    get  '/change', to: 'location#ask', as: 'location_ask'
    get  '/change2', to: 'location#change', as: 'location_change'
    post '/change', to: 'location#list'
    post '/change2', to: 'location#change'
  end

  # auth
  get '/auth/login', to: redirect('/es/user/login')
  get '/user/forgot', to: redirect('/es/user/reset/new')

  devise_for :users,
    :controllers => { :registrations => 'registrations' },
    path: 'user',
    path_names: {
      sign_up: 'register',
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset'
  }

  post '/addfriend/id/:id', to: 'friendships#create', as: 'add_friend'
  post '/deletefriend/:id', to: 'friendships#destroy', as: 'destroy_friend'

  scope '/admin' do
    get '/become/:id', to: 'admin#become', as: 'become_user'
    get '/lock/:id', to: 'admin#lock', as: 'lock_user'
    get '/unlock/:id', to: 'admin#unlock', as: 'unlock_user'
  end

  get '/user/edit/id/:id', to: redirect('/user/edit'), as: 'user_edit'
  get '/profile/:username', to: 'users#profile', as: 'profile'

  # comments
  post '/ad/:id/comments', to: 'comments#create', as: 'create_comment', commentable_type: 'Ad'

  # search
  get '/search', to: 'search#search', as: 'search'

  # messaging
  resources :mailboxer_messages, controller: :messages, path: "/messages/" do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end

  post 'messages/search', to: 'messages#search', as: "search_mailboxer_messages"

  # messaging legacy
  scope '/message' do
    get  '/received', to: redirect('/es/message/list'), as: 'messages_received'
    get  '/list', to: 'messages#index', as: 'messages_list'
    get  '/show/:id/subject/:subject', to: 'messages#show', as: 'message_show'
    get  '/create/id_user_to/:user_id', to: 'messages#new', as: 'message_new'
    get  '/create/id_user_to/:user_id/subject/:subject', to: "messages#new", as: 'message_new_with_subject'
    post '/create/id_user_to/:user_id', to: 'messages#create', as: 'message_create'
    post '/create/id_user_to/:user_id/subject/:subject', to: "messages#create", as: 'message_create_with_subject'
    post '/reply/:id/to/:user_id', to: 'messages#reply', as: 'message_reply'
  end

  # rss
  # nolotirov2 - legacy
  # FIX: las URLs legacy vienen asi
  # /en                     /rss/feed/woeid/766273                     /ad_type/give
  # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
  # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
  scope '/rss' do
    get '/feed/woeid/:woeid/ad_type/:type', format: 'rss', to: 'rss#feed', as: 'rss_type'
    get '/feed/woeid/:woeid/ad_type/give/status/:status', format: 'rss', to: 'rss#feed', as: 'rss_status'
  end

  # contact
  get '/contact', to: 'contact#new', as: 'contacts'
  post '/contact', to: 'contact#create'

end

app/views/partials/_footer.html.erb
<div id="footer">
  <div class="row">
    <div id="info" class="col-md-9 col-sm-9 col-xs-12">
      <h2>Quiénes somos</h2>
      <p>Prosalus es una organización no gubernamental de cooperación al desarrollo (ONGD) cuya misión es promover el respeto, protección y garantía de los derechos humanos a la alimentación, a la salud y al agua y saneamiento. Una de las líneas de trabajo de Prosalus está relacionada con el reconocimiento del derecho a la alimentación y un aspecto importante es la disminución del desperdicio de alimentos. Siguiendo la filosofía colaborativa, ponemos en marcha esta red que facilita el intercambio y la reducción del desperdicio. Esta iniciativa cuenta con la financiación de Territorios Solidarios de BBVA, el Ayuntamiento de Madrid  y con la colaboración del Centro de Innovación en Tecnología para el Desarrollo Humano (itdUPM).</p>
      <p>E-mail de contacto: <a href="mailto:cuentame@yonodesperdicio.org">cuentame@yonodesperdicio.org</a></p>
    </div><!--/info-->

    <div id="siguenos" class="col-md-3 col-sm-3 col-xs-12">
      <h2 class="enlinea col-md-4 col-sm-5 col-xs-4">Síguenos</h2>
      <p id="rrssf" class="col-md-8 col-sm-7 col-xs-8"> 
        <%= link_to(image_tag("rrss/twitter-48.png", :alt => "Twitter", :id => "twitter", :class=> "img-responsive"), "https://twitter.com/nodesperdicio", :target => "_blank") %>
        <%= link_to(image_tag("rrss/facebook-48.png", :alt => "Facebook", :id => "facebook", :class=> "img-responsive"), "https://www.facebook.com/yonodesperdicio", :target => "_blank") %>
        <%= link_to(image_tag("rrss/youtube-48.png", :alt => "YouTube", :id => "youtube", :class=> "img-responsive"), "https://www.youtube.com/user/Prosalus", :target => "_blank") %>
        <%= link_to(image_tag("rrss/flickr-48.png", :alt => "Flickr", :id => "flickr", :class=> "img-responsive"), "https://www.flickr.com/photos/prosalus/sets/72157658321641150", :target => "_blank") %>
      </p>
      <p id="logos" class="col-md-12 col-sm-12 col-xs-12"><a href="http://prosalus.es/" target="_blank">
        <%= image_tag("propias/logo-prosalus.png", :id => "logoprosalus", :alt => "Logo Prosalus") %>
      </a>
      <a href="http://www.un.org/es/zerohunger/#&panel1-1" target="_blank">
        <%= image_tag("propias/logo-reto-hambre-0.png", :id => "logohambre0", :alt => "Logo Reto Hambre Cero") %>
      </a></p>
    </div><!--/col-md-4-->
  </div><!--/footerone-->
</div><!--/footer-->

<div id="footertwo" class="row">
  <div class="links-left col-md-9 col-sm-7 col-xs-12">
    <ul>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to t('nlt.contact'), contact_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to ('Información legal'), legal_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to ('Mapa del sitio'), sitemap_path %></li>
      <li class="last col-md-3 col-sm-3 col-xs-3"><%= link_to t('nlt.faqs'), faqs_path %></li>
    </ul>
  </div><!--/links-left-->

  <div class="links-right col-md-3 col-sm-5 col-xs-12">
    <ul>
      <li class="col-md-6 col-sm-6 col-xs-6">DISEÑO:<br><%= link_to "Estudio blg", "http://estudioblg.com/" , { :target => "_blank" } %></li>
      <li class="last col-md-6 col-sm-6 col-xs-6">DESARROLLO:<br><%= link_to "Punto Abierto", "http://puntoabierto.net/" , { :target => "_blank" } %></li>
    </ul>
  </div><!--/links-right-->
</div><!--/footertwo-->

app/views/partials/_header.html.erb
<div id="header">
  <div id="menu-cabecera" class="row col-md-12">
    <ul>
      <li id="rrss" class="col-md-3 col-sm-3 col-xs-3"> 
        <%= link_to(image_tag("rrss/twitter-48.png", :alt => "Twitter", :id => "twitter", :class=> "img-responsive"), "https://twitter.com/nodesperdicio", :target => "_blank") %>
        <%= link_to(image_tag("rrss/facebook-48.png", :alt => "Facebook", :id => "facebook", :class=> "img-responsive"), "https://www.facebook.com/yonodesperdicio", :target => "_blank") %>
        <%= link_to(image_tag("rrss/youtube-48.png", :alt => "YouTube", :id => "youtube", :class=> "img-responsive"), "https://www.youtube.com/channel/UCzc9vB633AGfSO3mMy6Jpow", :target => "_blank") %>
        <%= link_to(image_tag("https://yonodesperdicio.org/assets/rrss/instagram-48.png", :alt => "Instagram", :id => "instagram", :class=> "img-responsive"), "https://www.instagram.com/yo_no_desperdicio/", :target => "_blank") %>
        <%#= link_to(image_tag("rrss/flickr-48.png", :alt => "Flickr", :id => "flickr", :class=> "img-responsive"), "https://www.flickr.com/photos/prosalus/sets/72157658321641150", :target => "_blank") #%>

     </li>
      <li id="comofunciona" class="col-md-2 col-sm-2 col-xs-4"><%= link_to 'Cómo funciona' , funciona_path %></li>
      <li id="login" class="col-md-2 col-sm-2 col-xs-4"><%= link_to t('nlt.login'), new_user_session_path, "data-no-turbolink" => true %></li>
      <li id="contacto" class="col-md-2 col-sm-2 col-xs-4"><%= link_to t('nlt.contact'), contact_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to t('nlt.faqs'), faqs_path %></li>
    </ul>
  </div><!--/menu-cabecera-->

  <div id="useractions" class="col-md-12 col-sm-12 col-xs-12">   
    <%= render :partial => "partials/user_actions" %>
  </div>

  <div class="row col-md-12 col-sm-12 col-xs-12">
  <div class="col-md-2 col-sm-2 hidden-xs">
    <%= image_tag "propias/Home-comida-izda.png", :alt => "imagen de comida", :id => "comida-izda", :class => "img-responsive" %>
  </div>

  <div class="col-md-8 col-sm-8 col-xs-12">
    <div class="site-name">
      <%= link_to root_path, :title => "yonodesperdicio.org home", "data-no-turbolink" => true do %>
      <%= image_tag "propias/cabecera-yonodesperdicio.png", :title => "Yonodesperdicio", :alt => "Yonodesperdicio", :id => "img-cabecera", :class => "img-responsive" %>
        <!--<h1>yonodesperdicio</h1>-->
        <%=h yield(:title) %>
      <% end %>
    </div>
  </div>

  <div class="col-md-2 col-sm-2 hidden-xs">
    <%= image_tag "propias/Home-comida-dcha.png", :alt => "imagen de comida", :id => "comida-dcha", :class => "img-responsive" %>
  </div>
  </div><!--/container-->


<div class="row homearriba col-md-12 col-xs-12">
  <div class="col-md-4 col-sm-4 col-xs-4">
    <%= link_to (image_tag "propias/Home-Brick.png", :alt => "Imagen brick para 'Comparte'", :id => "brick", :class => "img-responsive", :title => "Ver alimentos compartidos"), particulares_url %>
  </div>

  <div class="col-md-4 col-sm-4 col-xs-4">
    <%= link_to (image_tag "propias/Home-Recetas.png", :alt => "Imagen libro de recetas para 'Recetas y más...'", :id => "librorecetas", :class => "img-responsive", :title => "Ver trucos y recetas"), ideas_url(category: 'recetas') %>
  </div>

  <div class="col-md-4 col-sm-4 col-xs-4">
    <%= link_to (image_tag "propias/Home-Mapa.png", :alt => "Imagen gente para 'Organizaciones'", :id => "organizaciones", :class => "img-responsive", :title => "Ver organizaciones"), organizations_url %>
  </div>
</div><!--/homearriba-->


  <div id="botones" class="row col-md-12 col-sm-12 col-xs-12">
    <!--<div class="btn-ppales col-md-4 col-sm-4 col-xs-12">
      <div id="ios" class="btn btn-azul"><%#= link_to (image_tag "propias/googleplay.png", :alt => "Google Play", :class => "img-responsive"), "https://play.google.com/store/apps/details?id=com.imaginabit.yonodesperdicion", :target => '_blank' #%>
        <%#= link_to 'Descarga la app (iOS)', 'https://itunes.apple.com/us/app/yo-no-desperdicio/id1349176893?mt=8', :target => '_blank' #%>
      </div>
    </div>-->

    <div class="btn-ppales col-md-2 col-sm-2 col-xs-6">
      <div id="googleplay" class="btn btn-azul"><%#= link_to (image_tag "propias/btn-google-play-store.png", :alt => "Google Play", :class => "img-responsive"), "https://play.google.com/store/apps/details?id=com.imaginabit.yonodesperdicion", :target => '_blank' #%>
        <i class="fa fa-android" aria-hidden="true"></i>
        <%= link_to 'Google Play', 'https://play.google.com/store/apps/details?id=com.imaginabit.yonodesperdicion', :target => '_blank' %>
      </div>
    </div>

    <div class="btn-ppales col-md-2 col-sm-2 col-xs-6">
      <div id="ios" class="btn btn-azul col-md-6"><%#= link_to (image_tag "propias/btn-ios_app_store.png", :alt => "iOS Store", :class => "img-responsive"), "https://itunes.apple.com/us/app/yo-no-desperdicio/id1349176893?mt=8", :target => '_blank' #%>
        <i class="fa fa-apple" aria-hidden="true"></i>
        <%= link_to 'Apple Store', 'https://itunes.apple.com/us/app/yo-no-desperdicio/id1349176893?mt=8', :target => '_blank' %>
      </div>
    </div>
    <div class="btn-ppales col-md-4 col-sm-4 col-xs-12">
      <div class="btn btn-azul">
        <%= link_to t('nlt.new_user'), new_user_registration_path, "data-no-turbolink" => true %>
      </div>
    </div>
    <div class="btn-ppales col-md-4 col-sm-4 col-xs-12">
      <div class="btn btn-azul">
        <%= link_to 'Si te gusta ¡apóyanos!', 'https://prosalus.es/donacionesynd/formulario.php', :target => '_blank' %>
      </div>
    </div>
  </div>  

  <nav id="main-menu" class="row col-md-12 col-xs-12">
    <ul>
      <li><%= link_to root_path, :title => "Inicio", :class => menu_class('inicio'), "data-no-turbolink" => true do %>Inicio
      <% end %></li>
      <li><%= link_to 'noticias' , noticias_path, :class => menu_class('noticias') %></li>
      <li><%= link_to 'Ofertas', offers_path, class: menu_class('ofertas') %></li>
      <li>
        <div class="btn-group">
          <button type="button" dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= link_to 'ideas' , ideas_path, :class => menu_class('ideas') %>&nbsp;<span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Recetas", ideas_url(category: 'recetas'), :class => submenu_class('recetas') %></li>
            <li><%= link_to "Trucos", ideas_url(category: 'trucos'), :class => submenu_class('trucos') %></li>
          </ul>
        </div><!-- /btn-group -->
      </li>

      <li>
        <div class="btn-group">
          <button dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= link_to 'alimentos para compartir' , '#', :class => menu_class('compartir') %>&nbsp;<span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to 'Con organizaciones' , organizations_url, :class => submenu_class('organizaciones') %></li>
            <li><%= link_to 'Con particulares' , particulares_url, :class => submenu_class('particulares') %></li>
          </ul>
        </div><!-- /btn-group -->
      </li>  

      <li><%= link_to 'iniciativas sociales' , iniciativas_sociales_path, :class => menu_class('iniciativas') %></li>
    </ul>
  </nav>

  <% if content_for?(:action) %>
    <%= yield(:action) %>
  <% end %>

</div><!--/header-->

app/views/partials/_language.html.erb
<!-- for showing the i18n active lang -->
<% is_active_class = I18n.locale == abbr.to_sym ? "active" : "''" %>

<%= link_to params.merge({:locale => abbr}), :class => "flag-#{ abbr }  lang #{is_active_class}", "data-langcode" => abbr do %>
  <span><%= language %></span>
<% end %>

app/views/partials/_pagination.html.erb
<%= paginate items, inner_window: 2, outer_window: -1 %>

app/views/partials/_section_locations.html.erb
<div class="section_locations desktop">
  <h2><%= t('nlt.cities_in_the_world') %></h2>
  <br>
  <ul>
    <% AdHelper.get_locations_ranking(80).each do |loc| %>
      <li>
    <%= link_to ads_woeid_path(loc[1], :type => "give") do %>
      <%= loc[0] %> (<%= loc[2] %>) 
  <% end %>
    </li>
  <% end %>
  </ul>
</div>

<div class="section_locations mobile">
  <h2><%= t('nlt.cities_in_the_world') %></h2>
  <br>
  <ul>
    <% AdHelper.get_locations_ranking(20).each do |loc| %>
      <li>
    <%= link_to ads_woeid_path(loc[1], :type => "give") do %>
      <%= loc[0] %> (<%= loc[2] %>) 
  <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/partials/_section_users.html.erb
<div class="section_users desktop">
  <h2><%= t('nlt.users_most_active') %></h2>
  <br>
  <ul>
    <% AdHelper.get_users_ranking(80).each do |u| %>
      <li>
    <%= link_to listads_user_path u.id do %>
      <%= u.username %> (<%= u.ads_count %>)
  <% end %>
    </li>
  <% end %>
  </ul>
</div>

<div class="section_users mobile">
  <h2><%= t('nlt.users_most_active') %></h2>
  <br>
  <ul>
    <% AdHelper.get_users_ranking(20).each do |u| %>
      <li>
    <%= link_to listads_user_path u.id do %>
      <%= u.username %> (<%= u.ads_count %>)
  <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/partials/_sidebar_iniciativas.html.erb
  <h4>Iniciativas destacadas</h4>
  <ul>
  <% @iniciativas_destacadas.each do |iniciativa| %>
    <p><%= link_to iniciativa.title, iniciativa_url(iniciativa) %></p>
  <% end %>        
  </ul>


  <h4>Tweets</h4>
    <div id="tweets">
      <a class="twitter-timeline"  href="https://twitter.com/nodesperdicio" data-widget-id="638396445943533568" data-tweet-limit="3" data-chrome="nofooter">Tweets de @nodesperdicio.</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
  <h4>Links interesantes</h4>
  <%= text_for :links %>

app/views/partials/_sidebar_right.html.erb
  <h4>Noticias destacadas</h4>
  <ul>
  <% @noticias_destacadas.each do |noticia| %>
    <p><%= link_to noticia.title, noticia_url(noticia) %></p>
  <% end %>        
  </ul>


  <h4>Tweets</h4>
    <div id="tweets">
      <a class="twitter-timeline"  href="https://twitter.com/nodesperdicio" data-widget-id="638396445943533568" data-tweet-limit="3" data-chrome="nofooter">Tweets de @nodesperdicio.</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>

  <h4>Links interesantes</h4>
   <%= text_for :links %>

app/views/partials/_social_buttons.html.erb
<div id="social-buttons">

  <span id="twitter-button">
    <a class="twitter-share-button"  href="https://twitter.com/intent/tweet?url=<%= url %>&text=<%= meta_title %>" target="_blank"><i class="fa fa-twitter"></i></a>
  </span>

  <span id="facebook-button">
    <a href="https://www.facebook.com/sharer.php?u=<%= url %>" title="<%= meta_title %>" target="_blank" data-via="yonodesperdicio" data-layout="button_count"><i class="fa fa-facebook"></i></a>
  </span>

  <span id="google-button">
    <a href="https://plus.google.com/share?url={<%= url %>}" title="Compártelo en G+!" alt="Compártelo en G+!" data-via="yonodesperdicio" onclick="javascript:window.open(this.href,
  '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><i class="fa fa-google-plus"></i></a>
  </span>

</div>

app/views/partials/_user_actions.html.erb
<% if user_signed_in? %>
    <%= t('nlt.welcome') %>,
    <b>
      <%= link_to current_user.username, profile_path(current_user), id: 'js-username' %>
    </b> | 
    <% unread_messages_count = current_user.unread_messages_count %>
    <%= link_to messages_list_path, title: "#{unread_messages_count}" do %>
      <%= image_tag "icons/ico_email.gif" %>
      &nbsp;<b><%= unread_messages_count %></b>
    <% end %>
    |
    <%= link_to t('nlt.logout'), destroy_user_session_path, :method => :delete %>
<% else %>

<% end %>

app/views/partials/_you_have_to_sign_in.html.erb
<div id="default_header_section">
  <h1><%= t('nlt.to_publish_or_send_messages') %></h1>
  <br><br>
  (<%= t 'nlt.if_you_are_new' %>
  <%= link_to t('nlt.register_here'), new_user_registration_path, "data-no-turbolink" => true, :title => "user register" %>)
</div>