config/routes.rb
# require 'sidekiq/web'

Yonodesperdicio::Application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # authenticated :admin_user do
  #   mount Sidekiq::Web, at: "/sidekiq"
  # end

  root 'home#index'

  get '/noticias/(:tag)', to: 'home#noticias', as: 'noticias'
  get '/noticia/:id', to: 'home#noticia', as: 'noticia'
  post '/noticia/:id/comments', to: 'comments#create', as: 'noticia_comments', commentable_type: 'Article', article_category: 'noticia'

  get '/iniciativas_sociales/(:tag)', to: 'home#iniciativas_sociales', as: 'iniciativas_sociales'
  get '/iniciativa_social/:id', to: 'home#iniciativa', as: 'iniciativa'
  post '/iniciativa_social/:id/comments', to: 'comments#create', as: 'iniciativa_comments', commentable_type: 'Article', article_category: 'iniciativa'

  get '/ideas/(:category)', to: 'home#ideas', as: 'ideas'
  get '/ideas/de/:tag', to: 'home#ideas_tag', as: 'ideas_tag'
  get '/idea/:id', to: 'home#idea', as: 'idea'
  post '/idea/:id/comments', to: 'comments#create', as: 'idea_comments', commentable_type: 'Idea'

  get '/organizaciones', to: 'home#organizations', as: 'organizations'
  get '/organizacion/:id', to: 'home#organization', as: 'organization'

  get '/particulares', to: 'home#particulares', as: 'particulares'

  scope '/page' do
    get '/funciona', to: 'page#funciona', as: 'funciona'
    get '/faqs', to: 'page#faqs', as: 'faqs'
    get '/legal', to: 'page#legal', as: 'legal'
    get '/tos', to: 'page#tos', as: 'tos'
    get '/about', to: 'page#about', as: 'about'
    get '/privacy', to: 'page#privacy', as: 'privacy'
    get '/translate', to: 'page#translate', as: 'translate'
    get '/sitemap', to: 'page#sitemap', as: 'sitemap'
  end

  namespace :api, defaults: { format: :json } do
    get 'total_kg', to: 'base#total_kg'
    get 'categories', to: 'base#categories'
    get '', to: 'base#index'
    resources :users, :only => [:show, :create, :update, :destroy] do
      post 'rate', on: :member
    end
    resources :sessions, :only => [:create, :destroy]
    resources :ideas do
      resources :comments, :only => [:create]
    end
    resources :ads do
      resources :comments, :only => [:create]
    end
    resources :offers
    resources :mailboxes, :only => [:show] do
      resources :conversations, :only => [:index, :show] do
        resources :messages, :only => [:index, :create]
      end
    end
    get '/conversations', to: 'conversations#conversations'
    post '/new_message/(:recipient_id)', to: 'messages#new_message'
  end

  resources :ideas, path: 'mis_ideas', as: 'my_ideas'

  # FIXME: type on ads#create instead of params
  # FIXME: nolotirov2 legacy - redirect from /es/ad/create
  resources :ads, path: 'ad', path_names: { new: 'create' }

  scope '/ad' do
    #get '/create', to: redirect('/ad/create/type/1')
    get '/:id/:slug', to: 'ads#show', :as => 'adslug'
    get '/edit/id/:id', to: 'ads#edit', :as => 'ads_edit'
    get '/listall/ad_type/:type', to: 'woeid#show', as: "ads_listall"
    get '/listall/ad_type/:type/status/:status', to: 'woeid#show', as: 'ads_listall_status'
    get '/listall/page/:page/ad_type/:type', to: redirect('/ad/listall/ad_type/%{type}?page=%{page}')
    get '/listuser/id/:id', to: 'users#listads', as: 'listads_user'
  end

  resources :offers

  # locations lists
  get '/woeid/:id/:type', to: 'woeid#show', as: 'ads_woeid'
  get '/woeid/:id/:type/page/:page', to: redirect('/woeid/%{id}/%{type}?page=%{page}')
  get '/woeid/:id/:type/status/:status', to: 'woeid#show', as: 'ads_woeid_status'
  get '/woeid/:id/:type/page/:page/status/:status', to: redirect('/woeid/%{id}/%{type}/status/%{status}?page=%{page}')

  # location change
  scope '/location' do
    get  '/change', to: 'location#ask', as: 'location_ask'
    get  '/change2', to: 'location#change', as: 'location_change'
    post '/change', to: 'location#list'
    post '/change2', to: 'location#change'
  end

  # auth
  get '/auth/login', to: redirect('/es/user/login')
  get '/user/forgot', to: redirect('/es/user/reset/new')

  devise_for :users,
    :controllers => { :registrations => 'registrations' },
    path: 'user',
    path_names: {
      sign_up: 'register',
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset'
  }

  post '/addfriend/id/:id', to: 'friendships#create', as: 'add_friend'
  post '/deletefriend/:id', to: 'friendships#destroy', as: 'destroy_friend'

  scope '/admin' do
    get '/become/:id', to: 'admin#become', as: 'become_user'
    get '/lock/:id', to: 'admin#lock', as: 'lock_user'
    get '/unlock/:id', to: 'admin#unlock', as: 'unlock_user'
  end

  get '/user/edit/id/:id', to: redirect('/user/edit'), as: 'user_edit'
  get '/profile/:username', to: 'users#profile', as: 'profile'

  # comments
  post '/ad/:id/comments', to: 'comments#create', as: 'create_comment', commentable_type: 'Ad'

  # search
  get '/search', to: 'search#search', as: 'search'

  # messaging
  resources :mailboxer_messages, controller: :messages, path: "/messages/" do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end

  post 'messages/search', to: 'messages#search', as: "search_mailboxer_messages"

  # messaging legacy
  scope '/message' do
    get  '/received', to: redirect('/es/message/list'), as: 'messages_received'
    get  '/list', to: 'messages#index', as: 'messages_list'
    get  '/show/:id/subject/:subject', to: 'messages#show', as: 'message_show'
    get  '/create/id_user_to/:user_id', to: 'messages#new', as: 'message_new'
    get  '/create/id_user_to/:user_id/subject/:subject', to: "messages#new", as: 'message_new_with_subject'
    post '/create/id_user_to/:user_id', to: 'messages#create', as: 'message_create'
    post '/create/id_user_to/:user_id/subject/:subject', to: "messages#create", as: 'message_create_with_subject'
    post '/reply/:id/to/:user_id', to: 'messages#reply', as: 'message_reply'
  end

  # rss
  # nolotirov2 - legacy
  # FIX: las URLs legacy vienen asi
  # /en                     /rss/feed/woeid/766273                     /ad_type/give
  # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
  # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
  scope '/rss' do
    get '/feed/woeid/:woeid/ad_type/:type', format: 'rss', to: 'rss#feed', as: 'rss_type'
    get '/feed/woeid/:woeid/ad_type/give/status/:status', format: 'rss', to: 'rss#feed', as: 'rss_status'
  end

  # contact
  get '/contact', to: 'contact#new', as: 'contacts'
  post '/contact', to: 'contact#create'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    set_menu('inicio')
    @noticia = Article.where(category: 'noticia').
                      where("published_at < ?", Time.now).
                      order('published_at ASC').last
    @idea = Idea.where("published_at < ?", Time.now).
                 order('published_at ASC').last

    @alimentospro = Ad.give.includes(:user).
                        where(status: [1,2]).
                        where("pick_up_date IS NULL OR pick_up_date >= ?", Date.today).
                        where("created_at < ?", Time.now).
                        reorder('created_at DESC').first(3)
                        #order("created_at ASC").last(2)
    @offer=Offer.available.sample
  end

  # listado de noticias
  def noticias
    set_menu('noticias')
    if params[:tag].present?
      @noticias = Article.where(category: 'noticia').
                          where("published_at < ?", Time.now).
                          tagged_with(params[:tag]).
                          order('published_at DESC').
                          page(params[:page]).per(10)
    else
      @noticias = Article.where(category: 'noticia').
                          where("published_at < ?", Time.now).
                          order('published_at DESC').
                          page(params[:page]).per(10)
    end
    @noticias_destacadas = Article.where(category: 'noticia').
                                   where("published_at < ?", Time.now).
                                   where(pin: true).
                                   order('published_at DESC').limit(5)
    @noticias_archivo = Article.where(category: 'noticia').
                                where("published_at < ?", Time.now).
                                order('published_at DESC').limit(3)
  end

  # una noticia
  def noticia
    set_menu('noticias')
    @noticia = Article.where(category: 'noticia').
                       where("published_at < ?", Time.now).
                       includes(comments: :user).
                       friendly.
                       find(params[:id])
  end

  # listado de iniciativas
  def iniciativas_sociales
    set_menu('iniciativas')
    if params[:tag].present?
      @iniciativas = Article.where(category: 'iniciativa').
                             where("published_at < ?", Time.now).
                             tagged_with(params[:tag]).
                             order('published_at DESC').
                             page(params[:page]).per(10)
    else
      @iniciativas = Article.where(category: 'iniciativa').
                             where("published_at < ?", Time.now).
                             order('published_at DESC').
                             page(params[:page]).per(10)
    end

    @iniciativas_destacadas = Article.where(category: 'iniciativa').
                                      where("published_at < ?", Time.now).
                                      where(pin: true).order('published_at DESC').limit(5)
    @iniciativas_archivo = Article.where(category: 'iniciativa').
                                   where("published_at < ?", Time.now).
                                   order('published_at DESC').limit(3)
  end

  # una iniciativa
  def iniciativa
    set_menu('iniciativas')
    @iniciativa = Article.where(category: 'iniciativa').
                          where("published_at < ?", Time.now).
                          includes(comments: :user).
                          friendly.
                          find(params[:id])
  end



  # listado de ideas
  def ideas
    set_menu('ideas')
    category = params[:category]
    if category.present?
      set_submenu(category)
      @ideas = Idea.where(category: category).
                    where("published_at < ?", Time.now).
                    order('published_at DESC').
                    includes(:user).
                    page(params[:page]).per(6)
    else
      @ideas = Idea.where("published_at < ?", Time.now).
                    order('published_at DESC').
                    includes(:user).
                    page(params[:page]).per(6)
    end

    #Buscador de Ideas
    if params[:search]
      @ideas = Idea.search(params[:search]).
                    where("published_at < ?", Time.now).
                    order('published_at DESC').
                    includes(:user).
                    page(params[:page]).per(6)
    else
      @ideas = Idea.where(category: category).
                    where("published_at < ?", Time.now).
                    order('published_at DESC').
                    includes(:user).
                    page(params[:page]).per(6)
    end
  end

  def ideas_tag
    set_menu('ideas')
    tag = params[:tag]
    @ideas = Idea.where("published_at < ?", Time.now).
                  tagged_with(tag).
                  order('published_at DESC').
                  includes(:user).
                  page(params[:page]).per(6)
    render :ideas
  end

  # una idea
  def idea
    set_menu('ideas')
    @idea = Idea.where("published_at < ?", Time.now).
                 includes(comments: :user).
                 friendly.
                 find(params[:id])
    set_submenu(@idea.category.pluralize)
  end

  #listado de organizaciones
  def organizations
    #@organizations = Organization.order('name').
     #                             page(params[:page]).per(10)
    set_menu('compartir')
    set_submenu('organizaciones')

    #Buscador por CP de Organizaciones
    if params[:search]
      @organizations = Organization.search(params[:search]).
                                    order('name').
                                    page(params[:page]).per(10)
    else
      @organizations = Organization.order('name').
                                    page(params[:page]).per(10)
    end
  end #cierra listado organizaciones

  # una organizacion
  def organization
    @organization = Organization.friendly.
                                 find(params[:id])
    set_menu('compartir')
    set_submenu('organizaciones')
  end

  # listado de alimentos
  def particulares
    set_menu('compartir')
    set_submenu('particulares')

    #Alimentos disponibles y reservados y buscadores
    if params[:search] || params[:zipcode]
      @alimentos = Ad.give.includes(:user).
                           search(params[:search], params[:zipcode], params[:food_category]).
                           where(status: [1,2]).
                           where("pick_up_date IS NULL OR pick_up_date >= ?", Date.today).
                           page(params[:page]).per(12)
    else
      @alimentos = Ad.give.includes(:user).
                           where(status: [1,2]).
                           where("pick_up_date IS NULL OR pick_up_date >= ?", Date.today).
                           page(params[:page]).per(12)
    end

  end
end

app/views/home/idea.html.erb
<% content_for(:meta_title) {@idea.title} %>
<% content_for :meta_description do %>
  <meta name="description" content='<%= @idea.introduction %>' />
  <meta property="og:title" content="<%= @idea.introduction %>" />
  <meta property="og:image" content='<%= @idea.image.url %>' />
  <meta property="og:title" content='<%= @idea.title %>' />
  <meta itemprop="description" content="<%= strip_tags @idea.body %>" />
  <meta itemprop="image" content='<%= @idea.image.url %>' />
<% end %>


<div class="row">
  <div id="imagen" class="col-md-5">
    <%= image_tag @idea.image.url(:large), :alt => " ", :class => "img-responsive" %>
    <p>
      <% @idea.tag_list.each do |tag| %>
        <%= link_to tag, ideas_tag_url(tag: tag) %>,
      <% end %>
    </p>
    <p>
      <%= render :partial => "partials/social_buttons",
                 :locals => {
                    :url => idea_url(@idea),
                    :meta_title => @idea.title } %>
    </p>
  </div><!-- /imagen -->

  <div id="cuerpo" class="col-md-7">

    <h1 id="title"><%= @idea.title %></h1>
    <p class="fecha"><%= @idea.published_at.strftime("%d/%m/%Y") %> | Por: <strong><%= link_to @idea.user, profile_path(@idea.user.username) %></strong></p>
    <div class="intro"><%= markdown(@idea.introduction).html_safe if @idea.introduction %></div>


<% if @idea.ingredients.presence %>
    <h3 class="titulospeque"><%= t('¿Qué se necesita?') %></h3>
    <div class="ingredientes"><%= markdown(@idea.ingredients).html_safe if @idea.ingredients %></div>
  <% else %>

<% end %>

    <h3 class="titulospeque">¿Cómo se hace?</h3>
    <div class="como"><%= markdown(@idea.body).html_safe %></div>
    <p><i class="fa fa-arrow-left"></i><%= link_to ' VOLVER' , ideas_path %></p>

    <div id="comentarios">
      <p><b>COMENTAR</b>
      <% if !user_signed_in? %>
       <b>(Para dejar un comentario es necesario iniciar sesión)</b>
        <span class="login">
          <%= link_to t('nlt.login'), new_user_session_path, "data-no-turbolink" => true %>
        </span>
      <% end %>
      <div class="user_login_box"><%= render :partial => "partials/user_actions" %></div></p>

      <%= render :partial => "comments/form", :locals => {:path => idea_comments_path(@idea), :comment => Comment.new} %>
      <%= render :partial => "comments/list", :locals => {:comments => @idea.comments} %>
    </div><!--/comentarios-->

  </div><!-- /cuerpo -->
</div><!-- /row -->

app/views/home/ideas.html.erb
<% content_for(:meta_title) {"ideas"} %>

<div class="col-md-9 col-sm-9 col-xs-12">
<ul id="submenu">
  <li><%= link_to "Recetas", ideas_url(category: 'recetas'), :class => submenu_class('recetas') %></li>
  <li><%= link_to "Trucos", ideas_url(category: 'trucos'), :class => submenu_class('trucos') %></li>
</ul>
</div>

  <div class="col-md-3 col-sm-3 col-xs-12">
    <div id="menudcha">
      <%= form_tag(ideas_path, :method => "get", id: "buscadorideas") do %>
        <%= text_field_tag :search, params[:search], placeholder: "BUSCAR IDEAS" %>
        <%= button_tag(type: "submit", class: " ") do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        <% end %>
      <% end %>
    </div>
  </div>


  <% if params[:tag] %>
    <h1 id="title">Ideas frescas de <%= params[:tag] %></h1>
  <% end %>


  <% @ideas.each_slice(3) do |ideas| %>
    <div id="gridrecetas" class="col-md-12 col-sm-12 col-xs-12">
    <% ideas.each do |idea| %>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <%= link_to image_tag(idea.image.url(:medium), :alt => " ", :class => "img-responsive"), idea_url(idea) %>
        <h3 class="veinticinco"><%= link_to idea.title, idea_url(idea) %></h3>
        <div><%= idea.published_at.strftime("%d/%m/%Y") %>
        <span> | Por: <%= link_to idea.user, profile_path(idea.user.username) %></span></div>
        <div class="cuerpo">
         <%= link_to truncate_html(markdown(idea.introduction).html_safe, length: 200, omission: ' ... '), idea_url(idea) %>
        </div>
      </div><!--/col-md-4-->

    <% end %>
    </div><!--/gridrecetas-->
  <% end %>

<%= paginate(@ideas) %>


<div id="subereceta" class="row col-md-12 col-sm-12 col-xs-12">
  <div class="col-md-10 col-sm-10 col-xs-10">
    <span class="btn btn-rojo"><%= link_to 'Sube tu idea', new_my_idea_path %></span>
    <% unless user_signed_in? %>
      <span class="enrojo">  (Para subir tu receta o truco tienes que iniciar sesión)</span>
    <% end %>
  </div>
  <% unless user_signed_in? %>
    <div class="login col-md-2 col-sm-2 col-xs-2">
      <%= link_to t('nlt.login'), new_user_session_path, "data-no-turbolink" => true %>
    </div>
  <% end %>
</div><!-- /subereceta -->

app/views/home/index.html.erb
<%= content_for(:meta_title, "Yo no desperdicio") %>
<div id="alimentospro" class="row">
  <div class="col-md-9 col-xs-12">
  <h2>Alimentos para compartir</h2>
  <% @alimentospro.each_slice(3) do |alimentos| %>
    <% alimentos.each do |alimento| %>
      
      <div class="col-md-4 col-sm-4 col-xs-12">
      <div class="alimento">
        <%= link_to image_tag(alimento.image.url(:medium), :alt => " ", :class => "img-responsive"), adslug_path(id: alimento.id, slug: alimento.slug) %>
        <% if alimento.is_give? %>
          <span class="ad_status <%= alimento.status_class %>"><%= alimento.status_string %></span>
        <% end %>
          <h3 class="veinticinco"><%= link_to alimento.title, adslug_path(id: alimento.id, slug: alimento.slug) %></h3>
          <p class="cantidad"><%= grams_to_kg(alimento.grams) %> kg - <span><%= alimento.food_category %></span></p>
          <p>Código postal del alimento: <%= alimento.zipcode %></p>
          <p>Fecha límite de entrega: <%= formated_date(alimento.pick_up_date) %></p>

          <div id="usuario" class="row">
            <div id="izda" class="col-md-4">
              <%= image_tag alimento.user.image.url(:thumb), :alt => "", :class => "avatar, img-responsive" %>
            </div>
            <div id="dcha" class="col-md-8">
              <p class="username"><b><%= link_to alimento.user.username, profile_path(alimento.user.username) %></b></p>
              <p>Total comida entregada: <span id="comidaentregada"><%= grams_to_kg(alimento.user.total_quantity) %> kg</span></p>
            </div>

            <div id="editar" class="col-md-12"><% if can? :update, alimento %>
              <%= link_to ads_edit_path(alimento.id) do %>
                <div class="submit"><%= t('nlt.edit_this_ad') %></div>
              <% end %>
            <% end %>
            </div>
          </div><!--/usuario-->
        </div><!--/alimento-->
      </div><!--/col-md-6-->
    <% end %>
  <% end %>

<div id="masads" class="row">
  <%= link_to 'Ver +' , particulares_url %>
</div>
  </div>
  <%= render partial: "offers/offer", locals: { offer: @offer, title: true } %>
</div><!--/alimentospro-->


<div class="homenotideas col-sm-8 col-md-8 col-xs-12">
  <h2>Últimas noticias y recetas</h2>
  <div class="col-md-6 col-sm-6 col-xs-12">
    <!-- Una noticia -->
    <% if @noticia %>
      <%= link_to image_tag(@noticia.image.url(:fourthree), :alt => @noticia.title, :class => "img-responsive"), noticia_url(@noticia) %>
      <h3 class="veinticinco"><span>[Noticia] </span><%= link_to @noticia.title, noticia_url(@noticia) %></h3>
      <div class="cuerpazo"><%= link_to truncate_html(markdown(@noticia.body).html_safe, length: 200, omission: ' ... '), noticia_url(@noticia) %>
      </div>
    <% end %>
  </div>

  <div class="col-md-6 col-sm-6 col-xs-12">
    <!--<h2>Ideas</h2>-->
    <!-- Una idea -->
    <% if @idea %>
      <%= link_to image_tag(@idea.image.url(:fourthree), :alt => @idea.title, :class => "img-responsive"), idea_url(@idea) %>
      <h3 class="veinticinco"><span>[Idea] </span><%= link_to @idea.title, idea_url(@idea) %></h3>
      <div class="cuerpazo"><%= link_to truncate_html(markdown(@idea.introduction).html_safe, length: 200, omission: ' ... '), idea_url(@idea) if @idea.introduction %>
      </div>
    <% end %>
  </div>

</div><!--/homenotideas-->

<div class="col-md-4 col-sm-4 col-xs-12">
  <h2>Twitter</h2>
  <div id="tweets" class="col-md-12 col-sm-12 col-xs-12">
    <a class="twitter-timeline"  href="https://twitter.com/nodesperdicio" data-widget-id="638396445943533568" height="400">Tweets de @nodesperdicio.</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>
</div>

<div class="row">
<div class="homecontador col-md-12 col-xs-12">
  <div class="col-md-1 col-sm-1 col-xs-1">
    <%= image_tag "propias/cebolla.png", :alt => "Imagen cebolla", :id => "cebolla", :class => "img-responsive" %>
  </div>

  <div class="col-md-5 col-sm-5 col-xs-10">
    <div id="contador"><%= number_with_precision(great_total_quantity, :precision => 2, :delimiter => '.', :separator => "´") %> kg</div>
  </div>

  <div id="contador-texto" class="col-md-5 col-sm-5 col-xs-2">Son los kilos de comida que entre todos hemos conseguido evitar que acaben en la basura</div>

  <div class="col-md-1 col-sm-1 col-xs-1">
    <%= image_tag "propias/leche.png", :alt => "Imagen leche", :id => "leche", :class => "img-responsive" %>
  </div>
</div><!--/homecontador-->
</div><!--/row-->

app/views/home/particulares.html.erb
<% content_for(:meta_title) {"particulares"} %>

<div id="titalimentos" class="row">
  <div class="col-md-4 col-sm-4 col-xs-12">Entre particulares</div>
  <div class="col-md-8 col-sm-8 col-xs-12"><%= form_tag(particulares_path, :method => "get", id: "buscadorads") do %>
      <%= text_field_tag :search, params[:search], placeholder: "BUSCAR ALIMENTOS" %>
      <%= select_tag :food_category, options_for_select(Ad::FOOD_CATEGORIES, params[:food_category]), { prompt: "Categoría", include_blank: true } %>
      <%= text_field_tag :zipcode, params[:zipcode], placeholder: "CÓDIGO POSTAL" %>
      <%= button_tag(type: "submit", class: " ") do %>
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
      <% end %>
  <% end %></div>
</div>

  <% @alimentos.includes(:user).each_slice(4) do |alimentos| %>
  <div id="gridalimentos" class="row">

    <% alimentos.each do |alimento| %>

      <div class="col-md-3 col-sm-3 col-xs-12">
        <div class="alimento">
          <%= link_to image_tag(alimento.image.url(:medium), :alt => " ", :class => "img-responsive"), adslug_path(id: alimento.id, slug: alimento.slug) %>
          <% if alimento.is_give? %>
            <span class="ad_status <%= alimento.status_class %>"><%= alimento.status_string %></span>
          <% end %>
          <h3 class="veinticinco"><%= link_to alimento.title, adslug_path(id: alimento.id, slug: alimento.slug) %></h3>
          <p class="cantidad"><%= grams_to_kg(alimento.grams) %> kg - <span><%= alimento.food_category %></span></p>
          <p>Código postal del alimento: <%= alimento.zipcode %></p>
          <p>Fecha límite de entrega: <%= formated_date(alimento.pick_up_date) %></p>
          <hr>

          <div id="usuario" class="row">
            <div id="izda" class="col-md-4">
              <%= image_tag alimento.user.image.url(:thumb), :alt => "", :class => "avatar, img-responsive" %>
            </div>
            <div id="dcha" class="col-md-8">
              <p class="username"><b><%= link_to alimento.user.username, profile_path(alimento.user.username) %></b></p>
              <p>Total comida entregada: <span id="comidaentregada"><%= grams_to_kg(alimento.user.total_quantity) %> kg</span></p>
            </div>

            <div id="editar" class="col-md-12"><% if can? :update, alimento %>
              <%= link_to ads_edit_path(alimento.id) do %>
                <div class="submit"><%= t('nlt.edit_this_ad') %></div>
              <% end %>
            <% end %>
            </div>
          </div><!--usuario-->
        </div><!--/alimento-->
      </div><!--/col-md-3-->
    <% end %>

  </div><!--/gridalimentos-->
  <% end %>

<%= paginate(@alimentos) %>

<div id="subereceta" class="row col-md-12 col-sm-12 col-xs-12">
  <div class="col-md-10 col-sm-10 col-xs-10">
    <span class="btn btn-rojo"><%= link_to 'Comparte alimentos', new_ad_path %></span>
    <% unless user_signed_in? %>
      <span class="enrojo">  (Para compartir alimentos es necesario iniciar sesión)</span>
    <% end %>
  </div>
  <% unless user_signed_in? %>
  <div class="login col-md-2 col-sm-2 col-xs-2">
    <%= link_to t('nlt.login'), new_user_session_path, "data-no-turbolink" => true %>
  </div>
  <% end %>
</div><!-- /subereceta -->