config/routes.rb
# require 'sidekiq/web'

Yonodesperdicio::Application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # authenticated :admin_user do
  #   mount Sidekiq::Web, at: "/sidekiq"
  # end

  root 'home#index'

  get '/noticias/(:tag)', to: 'home#noticias', as: 'noticias'
  get '/noticia/:id', to: 'home#noticia', as: 'noticia'
  post '/noticia/:id/comments', to: 'comments#create', as: 'noticia_comments', commentable_type: 'Article', article_category: 'noticia'

  get '/iniciativas_sociales/(:tag)', to: 'home#iniciativas_sociales', as: 'iniciativas_sociales'
  get '/iniciativa_social/:id', to: 'home#iniciativa', as: 'iniciativa'
  post '/iniciativa_social/:id/comments', to: 'comments#create', as: 'iniciativa_comments', commentable_type: 'Article', article_category: 'iniciativa'

  get '/ideas/(:category)', to: 'home#ideas', as: 'ideas'
  get '/ideas/de/:tag', to: 'home#ideas_tag', as: 'ideas_tag'
  get '/idea/:id', to: 'home#idea', as: 'idea'
  post '/idea/:id/comments', to: 'comments#create', as: 'idea_comments', commentable_type: 'Idea'

  get '/organizaciones', to: 'home#organizations', as: 'organizations'
  get '/organizacion/:id', to: 'home#organization', as: 'organization'

  get '/particulares', to: 'home#particulares', as: 'particulares'

  scope '/page' do
    get '/funciona', to: 'page#funciona', as: 'funciona'
    get '/faqs', to: 'page#faqs', as: 'faqs'
    get '/legal', to: 'page#legal', as: 'legal'
    get '/tos', to: 'page#tos', as: 'tos'
    get '/about', to: 'page#about', as: 'about'
    get '/privacy', to: 'page#privacy', as: 'privacy'
    get '/translate', to: 'page#translate', as: 'translate'
    get '/sitemap', to: 'page#sitemap', as: 'sitemap'
  end

  namespace :api, defaults: { format: :json } do
    get 'total_kg', to: 'base#total_kg'
    get 'categories', to: 'base#categories'
    get '', to: 'base#index'
    resources :users, :only => [:show, :create, :update, :destroy] do
      post 'rate', on: :member
    end
    resources :sessions, :only => [:create, :destroy]
    resources :ideas do
      resources :comments, :only => [:create]
    end
    resources :ads do
      resources :comments, :only => [:create]
    end
    resources :offers
    resources :mailboxes, :only => [:show] do
      resources :conversations, :only => [:index, :show] do
        resources :messages, :only => [:index, :create]
      end
    end
    get '/conversations', to: 'conversations#conversations'
    post '/new_message/(:recipient_id)', to: 'messages#new_message'
  end

  resources :ideas, path: 'mis_ideas', as: 'my_ideas'

  # FIXME: type on ads#create instead of params
  # FIXME: nolotirov2 legacy - redirect from /es/ad/create
  resources :ads, path: 'ad', path_names: { new: 'create' }

  scope '/ad' do
    #get '/create', to: redirect('/ad/create/type/1')
    get '/:id/:slug', to: 'ads#show', :as => 'adslug'
    get '/edit/id/:id', to: 'ads#edit', :as => 'ads_edit'
    get '/listall/ad_type/:type', to: 'woeid#show', as: "ads_listall"
    get '/listall/ad_type/:type/status/:status', to: 'woeid#show', as: 'ads_listall_status'
    get '/listall/page/:page/ad_type/:type', to: redirect('/ad/listall/ad_type/%{type}?page=%{page}')
    get '/listuser/id/:id', to: 'users#listads', as: 'listads_user'
  end

  resources :offers

  # locations lists
  get '/woeid/:id/:type', to: 'woeid#show', as: 'ads_woeid'
  get '/woeid/:id/:type/page/:page', to: redirect('/woeid/%{id}/%{type}?page=%{page}')
  get '/woeid/:id/:type/status/:status', to: 'woeid#show', as: 'ads_woeid_status'
  get '/woeid/:id/:type/page/:page/status/:status', to: redirect('/woeid/%{id}/%{type}/status/%{status}?page=%{page}')

  # location change
  scope '/location' do
    get  '/change', to: 'location#ask', as: 'location_ask'
    get  '/change2', to: 'location#change', as: 'location_change'
    post '/change', to: 'location#list'
    post '/change2', to: 'location#change'
  end

  # auth
  get '/auth/login', to: redirect('/es/user/login')
  get '/user/forgot', to: redirect('/es/user/reset/new')

  devise_for :users,
    :controllers => { :registrations => 'registrations' },
    path: 'user',
    path_names: {
      sign_up: 'register',
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset'
  }

  post '/addfriend/id/:id', to: 'friendships#create', as: 'add_friend'
  post '/deletefriend/:id', to: 'friendships#destroy', as: 'destroy_friend'

  scope '/admin' do
    get '/become/:id', to: 'admin#become', as: 'become_user'
    get '/lock/:id', to: 'admin#lock', as: 'lock_user'
    get '/unlock/:id', to: 'admin#unlock', as: 'unlock_user'
  end

  get '/user/edit/id/:id', to: redirect('/user/edit'), as: 'user_edit'
  get '/profile/:username', to: 'users#profile', as: 'profile'

  # comments
  post '/ad/:id/comments', to: 'comments#create', as: 'create_comment', commentable_type: 'Ad'

  # search
  get '/search', to: 'search#search', as: 'search'

  # messaging
  resources :mailboxer_messages, controller: :messages, path: "/messages/" do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end

  post 'messages/search', to: 'messages#search', as: "search_mailboxer_messages"

  # messaging legacy
  scope '/message' do
    get  '/received', to: redirect('/es/message/list'), as: 'messages_received'
    get  '/list', to: 'messages#index', as: 'messages_list'
    get  '/show/:id/subject/:subject', to: 'messages#show', as: 'message_show'
    get  '/create/id_user_to/:user_id', to: 'messages#new', as: 'message_new'
    get  '/create/id_user_to/:user_id/subject/:subject', to: "messages#new", as: 'message_new_with_subject'
    post '/create/id_user_to/:user_id', to: 'messages#create', as: 'message_create'
    post '/create/id_user_to/:user_id/subject/:subject', to: "messages#create", as: 'message_create_with_subject'
    post '/reply/:id/to/:user_id', to: 'messages#reply', as: 'message_reply'
  end

  # rss
  # nolotirov2 - legacy
  # FIX: las URLs legacy vienen asi
  # /en                     /rss/feed/woeid/766273                     /ad_type/give
  # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
  # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
  scope '/rss' do
    get '/feed/woeid/:woeid/ad_type/:type', format: 'rss', to: 'rss#feed', as: 'rss_type'
    get '/feed/woeid/:woeid/ad_type/give/status/:status', format: 'rss', to: 'rss#feed', as: 'rss_status'
  end

  # contact
  get '/contact', to: 'contact#new', as: 'contacts'
  post '/contact', to: 'contact#create'

end

app/controllers/woeid_controller.rb
class WoeidController < ApplicationController

  #caches_action :show, :cache_path => Proc.new { |c| c.params }, unless: :current_user

  # GET /es/woeid/:id/:type
  # GET /es/woeid/:id/:type/status/:status
  # GET /es/ad/listall/ad_type/:type
  # GET /es/ad/listall/ad_type/:type/status/:status
  def show
    @id = params[:id]
    @type = params[:type]
    @status = params[:status].nil? ? 'available' : params[:status]

    case @status
    when 'available'
      st = 1
    when 'booked'
      st = 2
    when 'delivered'
      st = 3
    else
      st = 1
    end
    case @type
    when 'give'
      ty = 1
    when 'want'
      ty = 2
    else
      ty = 1
    end

    @ads = Ad.includes(:user).by_type(ty).by_status(st).by_woeid_code(@id).page(params[:page])

    if params.has_key?(:id)
      @woeid = WoeidHelper.convert_woeid_name params[:id]
    else
      @all = true # se trata de un listall
    end

    if not @ads.any?
      @location_suggest = get_location_suggest # no results
      if @woeid
        @location_options = WoeidHelper.search_by_name(@woeid[:short])
      end
    end
    render "show"
  end

end

app/helpers/woeid_helper.rb
module WoeidHelper

  def self.convert_woeid_name woeid
    # search by woeid, return place
    #
    # param woeid: integer. example: 244444
    # return place: string. format: "City, State, Country"
    #
    key = 'woeid_' + woeid.to_s
    if Rails.cache.fetch(key)
      return Rails.cache.fetch(key)
    else
      GeoPlanet.appid = Rails.application.secrets["geoplanet_app_id"]
      place_raw = GeoPlanet::Place.new(woeid.to_i, :lang => :es)
      #place =  { full: "#{place_raw.name}, #{place_raw.admin1}, #{place_raw.country}" , short: "#{place_raw.name}" }
      place =  { full: "#{place_raw.name}, #{place_raw.country}" , short: "#{place_raw.name}" }
      Rails.cache.write(key, place)
      return place
    end
  end

  def self.search_by_name name
    # search by name, return possible places
    #
    # param name: string. example: "Madrid"
    # return places: list. format: [[full name, woeid, ad_count], ...]
    #                      example: [["Madrid, Madrid, España (2444 anuncios)",766273],["Madrid, Comunidad de Madrid, España (444 anuncios)",12578024],["Madrid, Cundinamarca, Colombia (0 anuncios)",361938]]
    #
    key = 'location_' + name
    if Rails.cache.fetch(key)
      return Rails.cache.fetch(key)
    else
      GeoPlanet.appid = Rails.application.secrets["geoplanet_app_id"]
      locations = GeoPlanet::Place.search(name, :lang => :es, :count => 0)
      if locations.nil?
        places = nil
      else
        places = locations.map {|l| ["#{WoeidHelper.convert_woeid_name(l.woeid)[:full]} (#{Ad.where(woeid_code: l.woeid).count} anuncios)", l.woeid] }
      end
      Rails.cache.write(key, places)
      return places
    end
  end

end

app/views/woeid/_filter_status.html.erb
<div class="filter_status">        
  <% if all %>
    <%= link_to t('nlt.all'), ads_listall_path(type: 'give'),
      :class => status == "all" ? "actual" : "''" %>
    <%= link_to t('nlt.available'), ads_listall_status_path(type: 'give', status: 'available'),
      :class => status == "available" ? "actual" : "''" %>
    <%= link_to t('nlt.booked'), ads_listall_status_path(type: 'give', status: 'booked'),
      :class => status == "booked" ? "actual" : "''" %>
    <%= link_to t('nlt.delivered'), ads_listall_status_path(type: 'give', status: 'delivered'),
      :class => status == "delivered" ? "actual" : "''" %>
  <% else %>
    <%= link_to t('nlt.available'), ads_woeid_path(id: id, type: 'give'),
      :class => status == "available" ? "actual" : "''" %>
    <%= link_to t('nlt.booked'), ads_woeid_status_path(id: id, type: 'give', status: 'booked'), 
      :class => status == "booked" ? "actual" : "''" %>
    <%= link_to t('nlt.delivered'), ads_woeid_status_path(id: id, type: 'give', status: 'delivered'),
      :class => status == "delivered" ? "actual" : "''" %>
  <% end %>
</div>

app/views/woeid/show.html.erb
<%# content_for(:title, @woeid[:full]) if @woeid %>
<% content_for(:meta_title, t('nlt.keywords') + @woeid[:full]) if @ads_woeid_path %>

<% content_for :meta_description do %>
  <meta name="description" content="<%= t('nlt.gift_on', woeid: @woeid) %>. <%= t('nlt.meta_description') %>" />
<% end %>

<% unless @search or @all %>
  <% content_for :meta_extra do %>
    <link rel=”alternate” type=”application/rss+xml” title=”yonodesperdicio.org - <%= @woeid[:full] %>” href=”<%= rss_type_url(woeid: @id, type: @type, status: @status) %>” />
  <% end %>
<% end %>

<% content_for :action do %>
  <% type_n = @type == "want" ? 2 : 1 %>
  <% if @woeid%>
    <!--<div class="ad_create_tab">-->
    <div class="create-ad">
      <%= link_to "+ #{t('nlt.publish_ad_on', woeid: @woeid[:short])}", new_ad_path(type: type_n) %>
    </div>
  <% else %>
    <div class="ad_create_tab">
      <%= link_to "+ #{t('nlt.to_publish_ad')}", new_ad_path(type: type_n) %>
    </div>
  <% end %>
<% end %>

<div id="location_header_section">
  <% if @all %>
    <span class="give-want">
      <%= link_to t('nlt.give'), ads_listall_path(type: 'give'),
        :class => @type == "give" ? "actual" : "''" %>
      &nbsp;
      <%= link_to t('nlt.want'), ads_listall_path(type: 'want'), :class => @type == "want" ? "actual" : "''" %>
    </span>
  <div class="location_name">
    <h1><%= t('nlt.all_ads') %></h1>
    <br>
  </div>
  <% else %>
    <span class="give-want">
      <%= link_to t('nlt.give'), ads_woeid_path(id: @id, type: 'give'), :class => @type == "give" ? "actual" : "''" %>
      &nbsp;
      <%= link_to t('nlt.want'), ads_woeid_path(id: @id, type: 'want'), :class => @type == "want" ? "actual" : "''" %>
    </span>
    <div class="location_name">
      <h1>
        <% if @search %>
          <%= t('nlt.searching_on_html', q: @q) %>
        <% end %>
        <% if @type == "give" %>
          <%= t('nlt.give') %>
        <% else %>
          <%= t('nlt.want') %>
        <% end %>
        - <%= @woeid[:full] %>
      </h1>
      <br>
      <%= render :partial => "ads/search", :locals => {:woeid => @id, :ad_type => @type, :q => @q} %>
      <%= link_to location_ask_path, :class => "world_link" do %>
        <%= image_tag "change_location.png", :alt => "change location" %>
        <%= t('nlt.change_city') %>
      <% end %>
    </div>
  <% end %>
  </div>

  <div id="main">
    <div class="span-17">
      <% if @type == "give" %>
        <%= render :partial => "woeid/filter_status", :locals => {:status => @status, :id => @id, :all => @all} %>
      <% end %>

    <% if @ads.any? %>
      <% @ads.each_with_index do |ad,i| %>
        <%= render :partial => "ads/ad", :locals => { :ad => ad, :i => i, :show_ads => false } %>
      <% end %>
      <%= render partial: "partials/pagination", locals: { items: @ads } %>
    <% else %>
      <% if defined? @no_results_search %>
        <%= render :partial => "ads/no_results_search", :locals => { :location_suggest => @location_suggest, :location_options => @location_options } %>
      <% else %>
        <%= render :partial => "ads/no_results", :locals => { :location_suggest => @location_suggest, :location_options => @location_options, :woeid => @id } %>
      <% end %>
    <% end %>
      <% if @woeid %>
        <div class="rss">
          <%= link_to rss_type_path(:woeid => @id, :type => "give") do %>
            <%= image_tag "icons/rss.png", :alt => t("nlt.rss_suscribe") %>
            &nbsp; <%= t('nlt.rss_suscribe') %> - <%= @woeid[:full] %>
          <% end %>
        </div>
      <% end %>
    </div><!-- /span-17 -->
  </div>